"""Sentinel AI domain contracts: enums, value objects and versioned domain events.

This package has **no dependency on any framework or transport** -- it is pure domain and can
be imported by every service, the frontend build tooling (via schema export) and tests.
"""

from __future__ import annotations

from sentinel.contracts.base import FrozenModel, MutableModel, utcnow
from sentinel.contracts.enums import (
    AgentStatus,
    Axis,
    DecisionAction,
    DensityLevel,
    Direction,
    IncidentSeverity,
    IncidentType,
    SignalColor,
    SignalPhase,
    SystemMode,
    VehicleClass,
)
from sentinel.contracts.events import (
    EVENT_REGISTRY,
    AgentHeartbeat,
    BaselineUpdated,
    DecisionMade,
    DomainEvent,
    ExplanationGenerated,
    IncidentDetected,
    PredictionUpdated,
    SignalChanged,
    StateUpdated,
    SystemModeChanged,
    UnknownEventTypeError,
    deserialize_event,
)
from sentinel.contracts.value_objects import (
    AgentHealth,
    BoundingBox,
    Detection,
    Explanation,
    Forecast,
    HistoricalContext,
    Incident,
    IntersectionState,
    LaneBaseline,
    LaneForecast,
    LaneState,
    SignalCommand,
    SignalState,
    Track,
    Velocity,
)

__all__ = [
    "EVENT_REGISTRY",
    "AgentHealth",
    "AgentHeartbeat",
    "AgentStatus",
    "Axis",
    "BaselineUpdated",
    "BoundingBox",
    "DecisionAction",
    "DecisionMade",
    "DensityLevel",
    "Detection",
    "Direction",
    "DomainEvent",
    "Explanation",
    "ExplanationGenerated",
    "Forecast",
    "FrozenModel",
    "HistoricalContext",
    "Incident",
    "IncidentDetected",
    "IncidentSeverity",
    "IncidentType",
    "IntersectionState",
    "LaneBaseline",
    "LaneForecast",
    "LaneState",
    "MutableModel",
    "PredictionUpdated",
    "SignalChanged",
    "SignalColor",
    "SignalCommand",
    "SignalPhase",
    "SignalState",
    "StateUpdated",
    "SystemMode",
    "SystemModeChanged",
    "Track",
    "UnknownEventTypeError",
    "VehicleClass",
    "Velocity",
    "deserialize_event",
    "utcnow",
]
